name: Build Marlin for Malyan M300

on:
  push:
    branches: [ malyan-m300* ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v1
    - name: Install dependencies
      run: pip install platformio
    - name: show infos
      run: |
        platformio platform install ststm32@6.1.0 --with-package=framework-arduinoststm32
        pio_path=$(platformio lib --global list | grep Library | sed 's/Library Storage:\(.*\)lib/\1/')
        cd $pio_path
        #find $pio_path/packages/framework-arduinoststm32
        git init
        git remote add -f origin https://github.com/papabricole/Arduino_Core_STM32.git
        git reset --hard origin/malyan-m300
    - name: Build Marlin
      run: |
        platformio run -e malyan_M300
        mkdir firmware && touch firmware/fcupdate.flg
        mv .pio/build/malyan_M300/firmware.bin firmware/firmware.bin
    - name: show infos
      run: |
        pio_path=$(platformio lib --global list | grep Library | sed 's/Library Storage:\(.*\)lib/\1/')
        cd $pio_path
        git remote -v
        git describe
    - uses: actions/upload-artifact@v1
      with:
        name: firmware
        path: firmware

